### ISSUE TITLE
preg_replace with /e deprecated in PHP 5.5

### ISSUE THREAD

**Issue by pkarman** [inadarei/restagent#7]
http://us3.php.net//manual/en/function.preg-replace.php

**Comment by cavis** [comment]
FYI - I'm likely going to merge this into the PMP phpsdk as part of some other changes - publicmediaplatform/phpsdk/pull/17.

**Comment by inadarei** [comment]
Tests fixed and the PR is now merged into the upstream. Thanks for the nudge
