### ISSUE TITLE
PSR-4 and Composer

### ISSUE THREAD

**Issue by will-in-wi** [inadarei/restagent#9]
I have tried to update the lib to use PSR-4 and work with Composer. The work is in https://github.com/APMG/restagent/tree/psr4

It includes the commits for https://github.com/inadarei/restagent/pull/8, so I haven't submitted this as a pull request yet.

Does this interest you for inclusion?

I've also switched private methods to protected in https://github.com/APMG/restagent/tree/inheritance. The reasoning being that we have an internal lib which is a fork of this to handle our common authentication needs. If these methods and properties are given protected scope, we can inherit which makes things easier. This branch uses the PSR-4 work above.

I can send either or both branches as pull requests if they interest you.

Thanks!

**Comment by will-in-wi** [comment]
Is there any interest in this?

**Comment by inadarei** [comment]
Most definitely! Thanks!

**Comment by will-in-wi** [comment]
Would you like me to send a pull request, or will you pull and merge manually?

**Comment by inadarei** [comment]
Pull request is great. I see you already submitted one.
